### ISSUE TITLE
Code of Conduct revision

### ISSUE THREAD

**Issue by chartgerink** [epiverse-trace/.github#28]
I don't know when the code of conduct was last revised, but it appears to be out of date given the committee members are not all part of the project anymore. 

This issue is to track the known items that need to be revised, and provides a space to discuss what changes may need to be revised as well. 

This issue is to discuss purely technical/logistical details regarding the Code of Conduct, as I presume the substantive content is subject to the committee's decisions.

## Revision items

These items will be updated based on the discussion. 

- [ ] Add latest revision date to document
- [x] Where should input for feedback on the CoC go? Anna's email still mentioned (#34)
- ~~Review who has access to the Google Form and where this information goes upon submission~~
- ~~Review Google Form content itself (also mentions committee members no longer present)~~
- Committee membership
  - [ ] Anna Carnegie is no longer at LHSTM - remove
  - [x] Claudine Lim is no longer at data.org - remove (#34)
  - [ ] Do we add a new committee member for LHSTM?
  - [x] Do we add a new committee member for data.org? (#34)
  - [ ] Are the remaining committee members still up to date?
- ~~Mentions of "Community Manager" throughout the document may not be relevant anymore as there is no current community manager?~~
- [ ] "You may also make a report directly to one member of the Committee by contacting them directly" - no direct contact information is provided - do we add this? (best practice)

**Comment by Bisaloo** [comment]
Some updates that happened on slack / private communications but have not been publicized since it didn't reach full resolution yet:

- It seems that the process being the Google Form reporting workflow was lost when Anna left so it's been proposed to create a shared inbox for the CoC committee: `conduct@...`
- Cormekki volunteered to be the new data.org committee member
- UniAndes has a new committee member as well but I'm not sure who exactly

Some personal input on other points (not discussed with anyone else):

> Mentions of "Community Manager" throughout the document may not be relevant anymore as there is no current community manager?

I agree it makes sense to be more generic and not tie the phrasing to a specific position or job title which may or may not be filled at a given time.

> "You may also make a report directly to one member of the Committee by contacting them directly" - no direct contact information is provided - do we add this? (best practice)

Yes, I think it's important to offer the opportunity to report to a specific CoC member in some cases (e.g., conflict of interest or impossibility to maintain anonymity with another CoC member)
